services:
  postgres:
    image: postgres:17.4-alpine
    container_name: postgres_container
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    ports:
      - "5430:5432"
    env_file:
      - ./.env
    volumes:
      - ./pgdata:${PGDATA}
      - ./docker/postgres.conf:/usr/local/etc/postgres/postgres.conf
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: always

  redis:
    image: redis:7.4.2-alpine
    container_name: redis_container
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"
    env_file:
      - ./.env
    volumes:
      - ./redis_data:/data
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: [ "CMD-SHELL", "echo 'auth ${REDIS_PASSWORD} \n ping' | redis-cli | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: always

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local
